### ISSUE TITLE
UpdateCheck Issue

### ISSUE THREAD

**Issue by ImagicalGamer** [ImagicalGamer/SurvivalGames#171]
pocketmine\utils\Utils::getUrl() always returns 0 (using round() maybe), not sure how to fix (file_get_contents sucks, cURL doesn't work right on servers 100% of the time)

**Comment by GlitchPlayer** [comment]
Hmmm what do you use to check for update. I guessing its online right?

**Comment by ImagicalGamer** [comment]
pocketmine\utils\Utils::getUrl() to copy the version files contents and check if it's bigger than the configs version, it always returns 0, maybe because the version is 0.0.2?

**Comment by GlitchPlayer** [comment]
guys look what I fixed ;)
![image](https://cloud.githubusercontent.com/assets/16515013/17836634/78fc7aae-67cb-11e6-9187-08e85e6185e9.png)

**Comment by GlitchPlayer** [comment]
I fixed where it found an update :3
Im making a PR rn

**Comment by ImagicalGamer** [comment]
Okay

**Comment by ImagicalGamer** [comment]
Taki I thought your `else if` phobia was over

**Comment by Taki21** [comment]
nah some stupid bag of takis gave me it back...

**Comment by Taki21** [comment]
Please help me :( xD

**Comment by remotevase** [comment]
I just had a bag of takis... Im scared... the elseif(){} are knocking on my door... They are holding a giant semicolon... HELP!!!!!

**Comment by Taki21** [comment]
LOL! I hope the Takis Maker is not going crAzY

**Comment by Taki21** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/14851895/17905161/fd24728a-693f-11e6-90ee-455bc4f7682e.png)

**Comment by Taki21** [comment]
Life of a semi-colon....

**Comment by ImagicalGamer** [comment]
tbh I love using `else if`, it's better than `return` (in my opinion)

**Comment by Taki21** [comment]
xD
