### ISSUE TITLE
The future: Utilities Plugin!

### ISSUE THREAD

**Issue by remotevase** [ImagicalGamer/SurvivalGames#178]
In the near future, I see this plugin becoming a total "all-in-one" plugin. It would have Utilities such as UltimateRanks API, PurePerms API, S-W-Ultimate (see GitHub.com/remotevase/S-W-Ultimate and read SRC/plans.file), Economy API, and more. It will also have minigames such as SG, CTF, (maybe spleef), and maybe clans! What do you all think of the idea?

**Comment by ImagicalGamer** [comment]
So like a MiniGame core?

**Comment by ImagicalGamer** [comment]
I think we should make a minigame base that minigames can use to link together and make it more efficient, (kinda how pemapmodder and some ppls were doing be he left)

**Comment by remotevase** [comment]
Well, not exactly. You know how lifeboat core has a combination of 15 or so plugins? I am thinking of a different core. Not all minigames. Like 1/2 minigames, 1/2 Utilities/cool features

**Comment by Taki21** [comment]
OMG @ImagicalGamer is an octopus!

**Comment by remotevase** [comment]
Changed label to:
WARNING!!!! TAKIS CHIPS CAUSE ELSEIF(){} PHOBIA!!!!!!

**Comment by ImagicalGamer** [comment]
@Taki21 It's a squid but yas I got a new pp xD

**Comment by ImagicalGamer** [comment]
@remotevase We could start something new and do that but this is SG lmao

**Comment by Taki21** [comment]
lol
