### ISSUE TITLE
@remotevase

### ISSUE THREAD

**Issue by ImagicalGamer** [ImagicalGamer/SurvivalGames#187]
@remotevase I'm going to post this on IM forums, it's the latest and greatest ;)

**Comment by remotevase** [comment]
Well, the thing is- IM forums is practically dead except for the personal conversations

**Comment by ImagicalGamer** [comment]
ikr lol

**Comment by ImagicalGamer** [comment]
We should re activate that like we did my repos

**Comment by remotevase** [comment]
reactivate what?

**Comment by ImagicalGamer** [comment]
Bring IM forums back to life.

**Comment by remotevase** [comment]
Umm... Not gonna happen, sorry. I'm gonna spend the next 30 minutes creating a database of plugins (redistributed). It will be in html.

**Comment by ImagicalGamer** [comment]
Okay cool.

**Comment by remotevase** [comment]
Okay... Taking much longer than expected... Definitely gonna be done by Tuesday
