### ISSUE TITLE
How's this idea?

### ISSUE THREAD

**Issue by remotevase** [ImagicalGamer/SurvivalGames#190]
So... Do ya know how this is the number one SG Plugin for MCPE?

Well, it is. I feel like we should make it more universal. 

I have created an organization that is specifically for the SG plugin.I have invited Taki21&ImagicalGamer

This organization includes a HungerGames plugin-->We turn the SG plugin into a HG Plugin

This organization includes SurvivalGames repos that are specific to the server alt- Genysis or PHP7 Non-Genysis

Because of the seperate repo's, we will have something to do with the plugin: Fix compatibility issues. When compatibility issues are fixed, we can work on transforming it into a HG Plugin (simply remove the anti-block place/break and add an arena reset)

This organization will soon include an amazing website that showcases all of the plugin's features, as well as gives screenshots and more.

What do you think? @ImagicalGamer if u dont like it, I will delete it, but I feel that we should make the plugin into something even bigger than it is currently.  I hope you both like it, @Taki21 and @ImagicalGamer!

**Comment by ImagicalGamer** [comment]
I'm down

**Comment by remotevase** [comment]
I think that means yes?

**Comment by remotevase** [comment]
Oh just looked it up and it said that it means that you are cool with it! Awesome! See
https://github.com/MC-SG
All work is currently being done on the OriginalSG repo

**Comment by ImagicalGamer** [comment]
Okay
